<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use ADHhelper;

class SeedController extends Controller
{

    public function matkul()
    {
        $matkuls = [];
        $i = 0;
        foreach ($this->matkuls() as $dosen) {
            if ($dosen->kodemk != '') {
                $matkuls[$i]['kode'] = $dosen->kodemk;
                $matkuls[$i]['matkul'] = $dosen->namamatakuliah;
            }

            $i++;
        }
        
        \DB::table('matkul')->insert($matkuls);
    }

    private function matkuls() {
        return json_decode('
                    [
          {
            "id": 347,
            "idk": 18,
            "id_mk": 364,
            "date_log": "2019-08-08 09:54:12",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Pendidikan Agama",
            "kodemk": "MPK020418",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "1",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 350,
            "idk": 18,
            "id_mk": 367,
            "date_log": "2019-08-08 09:54:12",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Konsep Sistem Informasi",
            "kodemk": "MKK020218",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "1",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 353,
            "idk": 18,
            "id_mk": 370,
            "date_log": "2019-08-08 09:54:12",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Akuntansi",
            "kodemk": "MKK021718",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "1",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 349,
            "idk": 18,
            "id_mk": 366,
            "date_log": "2019-08-08 09:54:12",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Algoritma dan Pemrograman ",
            "kodemk": "MKK020118",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "1",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 352,
            "idk": 18,
            "id_mk": 369,
            "date_log": "2019-08-08 09:54:12",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Bahasa Indonesia",
            "kodemk": "MPK020518",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "1",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 355,
            "idk": 18,
            "id_mk": 372,
            "date_log": "2019-08-08 09:54:12",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Prak algoritma & pemrog",
            "kodemk": "MKK022118",
            "totalsks": 1,
            "teori": 0,
            "praktek": 1,
            "jenis": 1,
            "tingkat": "1",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 348,
            "idk": 18,
            "id_mk": 365,
            "date_log": "2019-08-08 09:54:12",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "PKN",
            "kodemk": "MPK020318",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "1",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 351,
            "idk": 18,
            "id_mk": 368,
            "date_log": "2019-08-08 09:54:12",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Kalkulus",
            "kodemk": "MKK022018",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "1",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 354,
            "idk": 18,
            "id_mk": 371,
            "date_log": "2019-08-08 09:54:12",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Bahasa Inggris 1",
            "kodemk": "MPK020118",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "1",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 362,
            "idk": 18,
            "id_mk": 446,
            "date_log": "2019-08-08 10:12:55",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Perencanaan Sistem Informasi",
            "kodemk": "MKB020418",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "2",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 356,
            "idk": 18,
            "id_mk": 437,
            "date_log": "2019-08-08 10:12:38",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Sistem Basis Data",
            "kodemk": "MKK020618",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "3",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 359,
            "idk": 18,
            "id_mk": 443,
            "date_log": "2019-08-08 10:12:38",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Keamanan JarKom",
            "kodemk": "MKB021718",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "3",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 358,
            "idk": 18,
            "id_mk": 442,
            "date_log": "2019-08-08 10:12:38",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "E-Bisnis",
            "kodemk": "MKB021018",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "3",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 361,
            "idk": 18,
            "id_mk": 445,
            "date_log": "2019-08-08 10:12:38",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Analisis Proses Bisnis",
            "kodemk": "MKB020118",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "3",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 357,
            "idk": 18,
            "id_mk": 438,
            "date_log": "2019-08-08 10:12:38",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Struktur Data",
            "kodemk": "MKK021318",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "3",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 360,
            "idk": 18,
            "id_mk": 444,
            "date_log": "2019-08-08 10:12:38",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Pemrograman Web ",
            "kodemk": "MKB020518",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "3",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 363,
            "idk": 18,
            "id_mk": 327,
            "date_log": "2019-08-08 10:13:36",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Perancangan Sistem Informasi",
            "kodemk": "MKB020503",
            "totalsks": 4,
            "teori": 3,
            "praktek": 1,
            "jenis": 1,
            "tingkat": "5",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 366,
            "idk": 18,
            "id_mk": 333,
            "date_log": "2019-08-08 10:13:36",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Keamanan Komputer",
            "kodemk": "MKK020616",
            "totalsks": 4,
            "teori": 2,
            "praktek": 2,
            "jenis": 1,
            "tingkat": "5",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 365,
            "idk": 18,
            "id_mk": 329,
            "date_log": "2019-08-08 10:13:36",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Pemrograman Orientasi Objek",
            "kodemk": "MKB020606",
            "totalsks": 4,
            "teori": 2,
            "praktek": 2,
            "jenis": 1,
            "tingkat": "5",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 368,
            "idk": 18,
            "id_mk": 335,
            "date_log": "2019-08-08 10:13:36",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Audit Sistem Informasi",
            "kodemk": "MKK020718",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "5",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 364,
            "idk": 18,
            "id_mk": 328,
            "date_log": "2019-08-08 10:13:36",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "E-Bisnis",
            "kodemk": "MKB020911",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "5",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 367,
            "idk": 18,
            "id_mk": 334,
            "date_log": "2019-08-08 10:13:36",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Metode Penelitian",
            "kodemk": "MKK020819",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 1,
            "tingkat": "5",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 369,
            "idk": 18,
            "id_mk": 349,
            "date_log": "2019-08-08 10:14:59",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Pengembangan E Bisnis",
            "kodemk": "MKB038216",
            "totalsks": 2,
            "teori": 2,
            "praktek": 0,
            "jenis": 2,
            "tingkat": "7",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 373,
            "idk": 18,
            "id_mk": 322,
            "date_log": "2019-08-08 10:14:59",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Kerja Praktek",
            "kodemk": "MBB020901",
            "totalsks": 4,
            "teori": 0,
            "praktek": 4,
            "jenis": 3,
            "tingkat": "7",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 371,
            "idk": 18,
            "id_mk": 351,
            "date_log": "2019-08-08 10:14:59",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Keamanan Jaringan Komputer",
            "kodemk": "MKB020810",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 2,
            "tingkat": "7",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 370,
            "idk": 18,
            "id_mk": 350,
            "date_log": "2019-08-08 10:14:59",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Sistem Penunjang Keputusan",
            "kodemk": "MKB020809",
            "totalsks": 4,
            "teori": 4,
            "praktek": 0,
            "jenis": 2,
            "tingkat": "7",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          },
          {
            "id": 374,
            "idk": 18,
            "id_mk": 323,
            "date_log": "2019-08-08 10:17:10",
            "idjurusan": 2,
            "idsemester": 21,
            "idjenjang": 1,
            "namakurikulum": "2019/2020 S1 Sistem Informasi",
            "jenjangpendidikan": "S1",
            "semester": "2019/2020 S1",
            "jurusan": "Sistem Informasi",
            "namamatakuliah": "Skripsi",
            "kodemk": "MBB021002",
            "totalsks": 6,
            "teori": 0,
            "praktek": 6,
            "jenis": 4,
            "tingkat": "8",
            "krsmulai": "2019-08-20",
            "krsselesai": "2019-09-15"
          }
        ]');
    }

    public function dosen()
    {
        $dosens = [];
        $i = 0;
        foreach ($this->dosens() as $dosen) {
            if ($dosen->nidn != '') {
                $dosens[$i]['nidn'] = $dosen->nidn;
                $dosens[$i]['nama'] = $dosen->nama;
            }

            $i++;
        }

        \DB::table('dosen')->insert($dosens);
    }

    private function dosens() {
        return json_decode('[
                              {
                                "id": 1,
                                "nama": "ANJAR SULASTIONO",
                                "nidn": "026065502",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1955-06-26",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "0819",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 2,
                                "nama": "ANTO PURWO SANTOSO",
                                "nidn": "0224117302",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1973-11-24",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 3,
                                "nama": " Apri Candra W,S.Kom., M.T.I",
                                "nidn": "0227048201",
                                "email": "apri.ican2704@gmail.com",
                                "niy": "",
                                "jk": "P",
                                "tempatlahir": "",
                                "tanggallahir": "1982-04-27",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Non Aktif",
                                "idjurusan": 1
                              },
                              {
                                "id": 4,
                                "nama": "DWI KARYAWATI",
                                "nidn": "0205058203",
                                "email": "",
                                "niy": "",
                                "jk": "P",
                                "tempatlahir": "",
                                "tanggallahir": "1982-05-05",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 5,
                                "nama": "EKA GERHAYU",
                                "nidn": "021106830",
                                "email": "",
                                "niy": "",
                                "jk": "P",
                                "tempatlahir": "",
                                "tanggallahir": "1983-06-11",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 6,
                                "nama": "EUIS MUSTIKA PRIYANGANTI",
                                "nidn": "0215057201",
                                "email": "",
                                "niy": "",
                                "jk": "P",
                                "tempatlahir": "",
                                "tanggallahir": "1972-05-15",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 7,
                                "nama": "HERI NURDIYANTO, S.Kom,M.T.I",
                                "nidn": "0203058701",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1987-05-03",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 1
                              },
                              {
                                "id": 8,
                                "nama": "ISMALIA AFRIANI",
                                "nidn": "017047501",
                                "email": "",
                                "niy": "",
                                "jk": "P",
                                "tempatlahir": "",
                                "tanggallahir": "1975-04-17",
                                "agama": 1,
                                "jenis_ptk": 127,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "197504172005012000",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 9,
                                "nama": "KURNIAWAN SAPUTRA",
                                "nidn": "024117304",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1973-11-24",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 10,
                                "nama": "KUSWANTO",
                                "nidn": "0206047803",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1978-04-06",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 11,
                                "nama": "M. Nur Ikhsanto, S.Kom, M.T.I",
                                "nidn": "0208028401",
                                "email": "ikhsanto@gmail.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1984-02-08",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 1
                              },
                              {
                                "id": 12,
                                "nama": "MACHUDOR YUSMAN M",
                                "nidn": "030035705",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1957-03-30",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "195703301986031000",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 13,
                                "nama": "NINING ISTI UTAMI",
                                "nidn": "0204107701",
                                "email": "",
                                "niy": "",
                                "jk": "P",
                                "tempatlahir": "",
                                "tanggallahir": "1977-10-04",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 14,
                                "nama": "R EKA GRALESMANA",
                                "nidn": "0210107002",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1970-10-10",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 15,
                                "nama": "REFLI DWIYANA",
                                "nidn": "0206108304",
                                "email": "",
                                "niy": "",
                                "jk": "P",
                                "tempatlahir": "",
                                "tanggallahir": "1983-10-06",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 16,
                                "nama": "Ridwan Yusuf, S.T, M.T.I",
                                "nidn": "0204077902",
                                "email": "ryusuf87@gmail.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1979-07-04",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 2
                              },
                              {
                                "id": 17,
                                "nama": "SEPTIAN DICKY CHANDRA, S.Si,M.T.I",
                                "nidn": "0214098501",
                                "email": "gerrardseptian14@yahoo.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1985-09-14",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 2
                              },
                              {
                                "id": 18,
                                "nama": "SUKRI ADI UTAMA",
                                "nidn": "0207098101",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1981-09-07",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 19,
                                "nama": "Surono,S.Kom,M.T.I",
                                "nidn": "0210078301",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1983-07-10",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 20,
                                "nama": "SYAFIUDDIN",
                                "nidn": "020016601",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1966-01-20",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "196601201991031000",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 21,
                                "nama": "TANFII DIAN ROHMAN",
                                "nidn": "0216128403",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1984-12-16",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 22,
                                "nama": "Tri Aristi Saputri, S.Kom., M.T.I",
                                "nidn": "0211018601",
                                "email": "arh1zty3@yahoo.co.id",
                                "niy": "",
                                "jk": "P",
                                "tempatlahir": "",
                                "tanggallahir": "1986-01-11",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 1
                              },
                              {
                                "id": 23,
                                "nama": "Untoro Apsiswanto, S.T., M.T.I",
                                "nidn": "0219047601",
                                "email": "untorostmikdw@gmail.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1976-04-19",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 2
                              },
                              {
                                "id": 43,
                                "nama": "Suprianto, S.Kom, M.T.I",
                                "nidn": "002",
                                "email": "chufrie@gmail.com",
                                "niy": "002",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1979-03-13",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 0
                              },
                              {
                                "id": 25,
                                "nama": "MISDIONO, SH",
                                "nidn": "",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1980-05-19",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 42,
                                "nama": "ROHANIA, S.Pd, M.Pd",
                                "nidn": "001",
                                "email": "",
                                "niy": "-",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1980-03-12",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 0
                              },
                              {
                                "id": 41,
                                "nama": "Benny Nurdianto, S.Kom",
                                "nidn": "004004136",
                                "email": "benny.stmikdw@gmail.com",
                                "niy": "004.004.136 D",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1980-03-21",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 40,
                                "nama": "Budi Sutomo, S.Kom, M.T.I",
                                "nidn": "0221038402",
                                "email": "budi.atmel@gmail.com",
                                "niy": "-",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1984-03-21",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 1
                              },
                              {
                                "id": 39,
                                "nama": "M. Reza Redo Islami, S.Kom, M.T.I",
                                "nidn": "0214118604",
                                "email": "reza.redo@hotmail.com",
                                "niy": "-",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1986-11-14",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 1
                              },
                              {
                                "id": 30,
                                "nama": "RIRIN WIDIANINGRUM, M.Pd, M.M",
                                "nidn": "016",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1980-05-19",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 46,
                                "nama": "Jevan Nelson, S.Kom",
                                "nidn": "006",
                                "email": "jevannelson@gmail.com",
                                "niy": "006",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1985-08-20",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 45,
                                "nama": "Irfan Nur Afni, ST., M.T.I",
                                "nidn": "004",
                                "email": "irfan.na@gmail.com",
                                "niy": "004",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1978-05-16",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 33,
                                "nama": "TOTO ANDRI, S.Kom,M.T.I",
                                "nidn": "",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1980-05-19",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 34,
                                "nama": "ARIF HIDAYAT, S.Kom,M.Kom",
                                "nidn": "",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1989-05-23",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 44,
                                "nama": "M. Adie Syaputra, S.Kom, M.T.I",
                                "nidn": "0225058601",
                                "email": "m4adie@gmail.com",
                                "niy": "003",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1982-05-16",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 1
                              },
                              {
                                "id": 36,
                                "nama": "DEWI ELIYANI, SE",
                                "nidn": "",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1980-05-19",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 38,
                                "nama": "NIZAMIYATI, S.Kom,M.Ti",
                                "nidn": "0220048704",
                                "email": "nizam.sisteminformasi@gmail.com",
                                "niy": "-",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1987-04-20",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 2
                              },
                              {
                                "id": 47,
                                "nama": "JUNI BAYU, S.Pd,M.Pd",
                                "nidn": "007",
                                "email": "satriamedian@yahoo.co.id",
                                "niy": "007",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1985-08-20",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 48,
                                "nama": "Arif Ismunandar, MM",
                                "nidn": "008",
                                "email": "arifismunandar86@gmail.com",
                                "niy": "008",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1985-08-20",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 49,
                                "nama": "Sita Muharni, S.Kom., M.T.I",
                                "nidn": "0226098502",
                                "email": "sita.stmikdcckotabumi@gmail.com",
                                "niy": "009",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1985-08-20",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 50,
                                "nama": "Drs. Wardaya, M.Pd",
                                "nidn": "010",
                                "email": "swardaya17@gmail.com",
                                "niy": "010",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1985-08-20",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 51,
                                "nama": "Haris Setiaji, S.Kom, M.T.I",
                                "nidn": "011",
                                "email": "harissetiajikom@gmail.com",
                                "niy": "011",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1985-08-20",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 52,
                                "nama": "Zainuddin, ST., M.T.I",
                                "nidn": "012",
                                "email": "gadisputri62@gmail.com",
                                "niy": "012",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1975-07-14",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 53,
                                "nama": "median satria",
                                "nidn": "004026267",
                                "email": "satriamedian26@gmail.com",
                                "niy": "004026267",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1990-06-12",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 54,
                                "nama": "EKA GUSTINA SARI",
                                "nidn": "004101152",
                                "email": "ekagustinasari13@gmail.com",
                                "niy": "004101152",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1985-08-13",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 55,
                                "nama": "Tri Budi Hartono, S.Kom",
                                "nidn": "004015227",
                                "email": "budi.spielberg@gmail.com",
                                "niy": "004015227",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1987-05-02",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 57,
                                "nama": "Ayu Umaka, SE,MM",
                                "nidn": "013",
                                "email": "ayuumaka08@gmail.com",
                                "niy": "-",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1995-03-05",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 58,
                                "nama": "Ade Sukma Arum, S,Pd",
                                "nidn": "014",
                                "email": "adearum@ymail.com",
                                "niy": "-",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "0000-00-00",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 60,
                                "nama": "Ade Sanjaya, MM",
                                "nidn": "015",
                                "email": "ade.sanjaya.sc@gmail.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1984-02-15",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 61,
                                "nama": "MUHAJIR, S.Kom.i",
                                "nidn": "017",
                                "email": "ahmadhajir05@gmail.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1982-03-11",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 62,
                                "nama": "BIGI UNDADRAJA, S.TP,M.Si",
                                "nidn": "018",
                                "email": "undadraja@yahoo.co.id",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1984-03-11",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "",
                                "idjurusan": 0
                              },
                              {
                                "id": 63,
                                "nama": "Ambar Pristia Rini, M.Pd",
                                "nidn": "019",
                                "email": "ambarpristia@gmail.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1987-01-05",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 3,
                                "status": "Aktif",
                                "idjurusan": 0
                              },
                              {
                                "id": 64,
                                "nama": "Andreas Perdana, S.Kom, M.T.I",
                                "nidn": "020",
                                "email": "andreasperdana.19@gmail.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "0000-00-00",
                                "agama": 3,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 0
                              },
                              {
                                "id": 65,
                                "nama": "YULDIKA PRASETYA",
                                "nidn": "021",
                                "email": "",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "0000-00-00",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "-",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 0
                              },
                              {
                                "id": 66,
                                "nama": "Bintang Ubamnata",
                                "nidn": "082176099413",
                                "email": "bintangubamnata@gmail.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "0000-00-00",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "082176099413",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 0
                              },
                              {
                                "id": 67,
                                "nama": "Yuspa Fitri Meza,S.Pd",
                                "nidn": "022",
                                "email": "yuspafitrimeza@yahoo.com",
                                "niy": "",
                                "jk": "L",
                                "tempatlahir": "",
                                "tanggallahir": "1970-01-01",
                                "agama": 1,
                                "jenis_ptk": 0,
                                "tlp_hp": "",
                                "alamat": "",
                                "tlp_rumah": "",
                                "nik": "",
                                "idhomebase": 1,
                                "status": "Aktif",
                                "idjurusan": 0
                              }
                            ]');
    }

}